
// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Diary of a Wimpy Kid",
    url: "https://m.media-amazon.com/images/I/81R2N4PRuUL._SY342_.jpg",
    hardcoverPrice: 14.89,
    paperbackPrice: 6.69,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Can You Get Rainbows in Space?",
    url: "https://m.media-amazon.com/images/I/81iJLB0L-cL._SY342_.jpg",
    hardcoverPrice: 14.98,
    paperbackPrice: 12.29,
    rating: 5,
  },
  {
    id: 3,
    title: "The Giant Book of Who, What, When, Where, Why & How",
    url: "https://m.media-amazon.com/images/I/91-ag3IkIdS._SY342_.jpg",
    hardcoverPrice: 33.64,
    paperbackPrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Pippi Longstocking",
    url: "https://m.media-amazon.com/images/I/91PkmM4CLML._SY342_.jpg",
    hardcoverPrice: 3.88,
    paperbackPrice: 8.90,
    rating: 4.5,
  },
  {
    id: 5,
    title: "My First Coding Book",
    url: "https://m.media-amazon.com/images/I/61ZzFzLEQrL._SY342_.jpg",
    hardcoverPrice: null,
    paperbackPrice: 9.76,
    rating: 5,
  },
  {
    id: 6,
    title: "Chicken Soup for the Kid's Soul",
    url: "https://m.media-amazon.com/images/I/81COmOGnrrL._SY342_.jpg",
    hardcoverPrice: 37.11,
    paperbackPrice: 20.26,
    rating: 5,
  },
  {
    id: 7,
    title: "The Cat in the Hat",
    url: "https://m.media-amazon.com/images/I/71V9MimRMSL._SY342_.jpg",
    hardcoverPrice: 8.37,
    paperbackPrice: 10.79,
    rating: 5,
  },
  {
    id: 8,
    title: "The Cat in the Hat Comes Back",
    url: "https://m.media-amazon.com/images/I/81H4EvAZBIL._SY342_.jpg",
    hardcoverPrice: 5.79,
    paperbackPrice: 6.99,
    rating: 5,
  },
  {
    id: 9,
    title: "The Everything Kids' Astronomy Book",
    url: "https://m.media-amazon.com/images/I/71b9uKb1W0L._SY342_.jpg",
    hardcoverPrice: null,
    paperbackPrice: 8.70,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Charlotte's Web",
    url: "https://m.media-amazon.com/images/I/91B3luFcjwL._SY385_.jpg",
    hardcoverPrice: 12.99,
    paperbackPrice: 11.20,
    rating: 5,
  },
  {
    id: 11,
    title: "My Very First Bible Stories - Board Book",
    url: "https://m.media-amazon.com/images/I/81KlRPnGrRL._SY342_.jpg",
    hardcoverPrice: 11.20,
    paperbackPrice: null,
    rating: 5,
  },
  {
    id: 12,
    title: "German English Illustrated Dictionary",
    url: "https://m.media-amazon.com/images/I/81U+CctJxCL._SY342_.jpg",
    hardcoverPrice: 24.88,
    paperbackPrice: null,
    rating: 4.5,
  },
  {
    id: 13,
    title: "The Big Book of Bugs",
    url: "https://m.media-amazon.com/images/I/81lzcY4PgPL._SY342_.jpg",
    hardcoverPrice: 18.65,
    paperbackPrice: null,
    rating: 4.9,
  },
  {
    id: 14,
    title: "Plant the Tiny Seed",
    url: "https://m.media-amazon.com/images/I/71YQ2-oyyFL._SY342_.jpg",
    hardcoverPrice: 16.00,
    paperbackPrice: 7.90,
    rating: 4.8,
  },
  {
    id: 15,
    title: "Up in the Garden and Down in the Dirt",
    url: "https://m.media-amazon.com/images/I/51cvyHKXYnL._SY445_SX342_QL70_ML2_.jpg",
    hardcoverPrice: 17.40,
    paperbackPrice: 7.98,
    rating: 4.8,
  },
  {
    id: 16,
    title: "Roald Dahl's Marvellous Joke Book",
    url: "https://m.media-amazon.com/images/I/81g9Y2yBtHL._SY342_.jpg",
    hardcoverPrice: 8.39,
    paperbackPrice: 1.77,
    rating: 4.5,
  },
];